# Generated by Django 3.1.2 on 2021-05-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='')),
                ('address', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Launderer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='')),
                ('address', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Launderette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('available_time', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_photo', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='')),
                ('location', models.CharField(max_length=200, null=True)),
                ('launderer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderer')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(default=0)),
                ('available_balance', models.FloatField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
                ('launderette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderette')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.ImageField(blank=True, default='default-profile.png', null=True, upload_to='')),
                ('launderette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderette')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
                ('launderette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderette')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(default=0)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('finished', 'Finished'), ('ongoing', 'Ongoing'), ('declined', 'Declined')], default='pending', max_length=50, null=True)),
                ('date_started', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_end', models.DateTimeField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
                ('launderette', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderette')),
                ('services', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.services')),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('sent', 'Sent')], default='pending', max_length=50, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
                ('launderette', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderette')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, null=True)),
                ('complain', models.CharField(max_length=500, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client')),
            ],
        ),
    ]
