# Generated by Django 3.1.2 on 2021-09-17 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='launderer',
            name='bio',
        ),
    ]
