# Generated by Django 3.1.2 on 2021-09-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_launderette_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launderette',
            name='cover_photo',
            field=models.ImageField(blank=True, default='0_GettyImages-1068728612.jpg.png', null=True, upload_to=''),
        ),
    ]
