# Generated by Django 3.1.2 on 2021-09-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210918_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launderette',
            name='cover_photo',
            field=models.ImageField(blank=True, default='0_GettyImages-1068728612.jpg', null=True, upload_to=''),
        ),
    ]
