# Generated by Django 3.1.2 on 2021-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210918_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
