# Generated by Django 3.1.2 on 2021-09-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20210920_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(null=True),
        ),
    ]
