# Generated by Django 3.1.2 on 2021-09-20 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_review_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
    ]
