# Generated by Django 3.1.2 on 2021-09-20 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
