# Generated by Django 3.1.2 on 2021-09-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0015_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='isBlocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='launderer',
            name='isBlocked',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='launderette',
            name='isBlocked',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
