# Generated by Django 3.1.2 on 2021-10-06 02:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0017_auto_20210923_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='launderer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderer'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'resolved'), ('closed', 'Closed')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='launderer',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='launderer',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='launderer',
            name='profile_pic',
            field=models.ImageField(default='default-profile.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='launderette',
            name='cover_photo',
            field=models.ImageField(default='0_GettyImages-1068728612.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='launderette',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='launderette',
            name='isBlocked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='services',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
