# Generated by Django 3.1.2 on 2021-10-06 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_auto_20211006_0729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.client'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='launderer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.launderer'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('unresolved', 'Unresolved'), ('resolved', 'resolved'), ('closed', 'Closed')], default='unresolved', max_length=50, null=True),
        ),
    ]
