# Generated by Django 3.1.2 on 2021-10-14 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0020_complaint_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('sent', 'Sent'), ('late', 'Late')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('finished', 'Finished'), ('ongoing', 'Ongoing'), ('declined', 'Declined'), ('canceled', 'Canceled')], default='pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
