# Generated by Django 3.1.2 on 2021-12-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0023_auto_20211206_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='lon',
            field=models.FloatField(default=0),
        ),
    ]
