# Generated by Django 3.1.2 on 2021-12-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0024_auto_20211206_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='launderer',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
