# Generated by Django 3.1.2 on 2021-12-13 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0027_auto_20211213_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='hasdelivery',
            field=models.BooleanField(default=False),
        ),
    ]
