# Generated by Django 3.1.2 on 2021-12-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0028_order_hasdelivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
