# Generated by Django 3.1.2 on 2021-12-13 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0029_auto_20211213_1733'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hasdelivery',
        ),
    ]
