# Generated by Django 3.1.2 on 2021-12-13 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0032_auto_20211213_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='launderer',
            name='easypaisa_account',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
