# Generated by Django 3.1.2 on 2021-12-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0033_launderer_easypaisa_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='launderer',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='launderette',
            options={'ordering': ['-date_joined']},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='reviewcomment',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['-date']},
        ),
    ]
